#!/usr/bin/env bash
# Install a global `dsh` command that runs the DeepSeek Harness CLI straight
# from a source checkout — WITHOUT changing the caller's cwd (dsh uses the
# invoking directory as its default workspace root, so `cd` would break it).
#
#   install_global_dsh.sh                          # auto-detect the checkout
#   install_global_dsh.sh ~/evn/deepseek-harness
#   install_global_dsh.sh ~/src/dsh --bin-dir ~/bin --force
#
# Env:
#   DSH_BIN_DIR  target bin dir (default: ~/.local/bin)
#   DSH_NODE     preferred node binary recorded in the wrapper

set -uo pipefail

REPO=""
BIN_DIR="${DSH_BIN_DIR:-$HOME/.local/bin}"
NAME="dsh"
FORCE=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --bin-dir) [[ $# -ge 2 ]] || { printf '%s needs a value\n' "$1" >&2; exit 2; }; BIN_DIR="$2"; shift 2 ;;
    --name)    [[ $# -ge 2 ]] || { printf '%s needs a value\n' "$1" >&2; exit 2; }; NAME="$2"; shift 2 ;;
    --force)   FORCE=1; shift ;;
    -h|--help) sed -n '2,14p' "$0" | sed 's|^# \{0,1\}||'; exit 0 ;;
    -*)        printf 'unknown flag: %s\n' "$1" >&2; exit 2 ;;
    *)         REPO="$1"; shift ;;
  esac
done

want() { printf '\n== %s\n' "$*"; }
die() { printf 'error: %s\n' "$*" >&2; exit 1; }

# --- locate the checkout -----------------------------------------------------
if [[ -z "$REPO" ]]; then
  for cand in "$HOME/evn/deepseek-harness" "$HOME/env/deepseek-harness" \
              "$HOME/deepseek-harness" "$HOME/src/deepseek-harness" \
              "$HOME/workspace/deepseek-harness" "$HOME/code/deepseek-harness"; do
    if [[ -f "$cand/apps/cli/package.json" ]]; then REPO="$cand"; break; fi
  done
fi
[[ -n "$REPO" ]] || die "could not find a deepseek-harness checkout; pass the path explicitly"
[[ -f "$REPO/apps/cli/package.json" ]] || die "not a deepseek-harness checkout: $REPO"
REPO="$(cd "$REPO" && pwd)"
want "checkout: $REPO"

VERSION="$(python3 -c "import json;print(json.load(open('$REPO/apps/cli/package.json'))['version'])" 2>/dev/null || echo unknown)"
printf '   cli version: %s\n' "$VERSION"

ENTRY="$REPO/apps/cli/lib/bin.js"
if [[ ! -f "$ENTRY" ]]; then
  printf '   WARNING: build artifacts missing (%s)\n' "apps/cli/lib/bin.js"
  printf '   The command will not work until you run:\n'
  printf '     cd %s && pnpm install && pnpm run build\n' "$REPO"
fi

# --- verify a usable node ----------------------------------------------------
NODE_OK=""
for n in "${DSH_NODE:-}" "$(command -v node)" /opt/homebrew/bin/node /usr/local/bin/node; do
  [[ -n "$n" && -x "$n" ]] || continue
  v="$("$n" -p 'process.versions.node' 2>/dev/null)" || continue
  major="${v%%.*}"; minor="${v#*.}"; minor="${minor%%.*}"
  [[ "$major" =~ ^[0-9]+$ ]] || continue
  if (( major >= 24 )) || (( major == 22 && minor >= 19 )); then NODE_OK="$n ($v)"; break; fi
done
if [[ -n "$NODE_OK" ]]; then printf '   node: %s\n' "$NODE_OK"
else printf '   WARNING: no node satisfying ^22.19.0 || >=24.0.0 found on this PATH\n'; fi

# --- write the wrapper -------------------------------------------------------
mkdir -p "$BIN_DIR" || die "cannot create $BIN_DIR"
TARGET="$BIN_DIR/$NAME"
if [[ -e "$TARGET" && $FORCE -ne 1 ]]; then
  die "$TARGET already exists (use --force to overwrite)"
fi

cat > "$TARGET" <<WRAPPER
#!/usr/bin/env bash
# $NAME — DeepSeek Harness CLI from the source checkout at $REPO
# Generated by deepseek-harness-skill/scripts/install_global_dsh.sh
# Deliberately does NOT \`cd\`: dsh treats the invoking directory as its default
# workspace root, so the caller's cwd must be preserved.
#
# Env overrides: DSH_REPO (checkout path), DSH_NODE (node binary).

DSH_REPO="\${DSH_REPO:-$REPO}"
ENTRY="\$DSH_REPO/apps/cli/lib/bin.js"

die() { printf '$NAME: %s\n' "\$*" >&2; exit 1; }

[ -d "\$DSH_REPO" ] || die "repo not found at \$DSH_REPO (set DSH_REPO to override)"
[ -f "\$ENTRY" ] || die "build artifacts missing: \$ENTRY
  Run:  cd \$DSH_REPO && pnpm install && pnpm run build"

# Harness requires node ^22.19.0 || >=24.0.0. Try candidates in order and use
# the first that satisfies the range, instead of failing opaquely.
pick_node() {
  local n v major minor
  for n in "\$DSH_NODE" "\$(command -v node)" /opt/homebrew/bin/node /usr/local/bin/node; do
    [ -n "\$n" ] || continue
    [ -x "\$n" ] || continue
    v=\$("\$n" -p 'process.versions.node' 2>/dev/null) || continue
    major=\${v%%.*}
    minor=\${v#*.}; minor=\${minor%%.*}
    case "\$major" in ''|*[!0-9]*) continue ;; esac
    if [ "\$major" -ge 24 ] || { [ "\$major" -eq 22 ] && [ "\$minor" -ge 19 ]; }; then
      printf '%s' "\$n"; return 0
    fi
  done
  return 1
}

NODE="\$(pick_node)" || die "no compatible node found (need ^22.19.0 || >=24.0.0)
  Found '\$(command -v node || echo none)' -> \$("\$(command -v node)" -v 2>/dev/null || echo n/a)
  Install Node 24+ or set DSH_NODE=/path/to/node"

exec "\$NODE" "\$ENTRY" "\$@"
WRAPPER

chmod 755 "$TARGET" || die "chmod failed on $TARGET"
want "installed: $TARGET"

# --- report PATH status ------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) printf '   %s is on PATH — run: %s --version\n' "$BIN_DIR" "$NAME" ;;
  *)
    printf '   WARNING: %s is NOT on your PATH. Add this to ~/.zshrc:\n' "$BIN_DIR"
    printf '     export PATH="%s:$PATH"\n' "$BIN_DIR"
    ;;
esac

# --- shadowing check ---------------------------------------------------------
for d in "$HOME/Library/pnpm/bin" /opt/homebrew/bin /usr/local/bin; do
  if [[ -e "$d/$NAME" && "$d/$NAME" != "$TARGET" ]]; then
    printf '   NOTE: another %s exists at %s and may shadow this one depending on PATH order.\n' \
      "$NAME" "$d/$NAME"
  fi
done
